language: julia
os:
  - linux
  - osx
  - windows
  - freebsd
arch:
  - amd64
  - i386
  - arm64
julia:
  - 1.6.1
  - nightly
notifications:
  email: false
codecov: true
coveralls: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
jobs:
  include:
    - stage: "Documentation"
      julia: 1.6.1
      os: windows
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip