language: julia
os:
  - linux
  - osx
  - windows
  - freebsd
arch:
  - amd64
  - i386
  - arm64
julia:
  - 1.6.1
  - nightly
notifications:
  email: false
codecov: true
coveralls: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("SpeedMapping.jl")); include(joinpath("docs", "make.jl"))'

  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                          Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip