language: julia
os:
  - linux
  - osx
  - windows
  - freebsd
arch:
  - amd64
  - i386
  - arm64
julia:
  - 1.6.1
  - nightly
notifications:
  email: false
codecov: true
coveralls: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';